exchanges:
  binance:
    enabled: true
    testnet: false
    symbols:
      - "BTC/USDT:PERP"
      - "ETH/USDT:PERP"
      - "BNB/USDT:PERP"
      - "XRP/USDT:PERP"
      - "SOL/USDT:PERP"
      - "TRX/USDT:PERP"
      - "HYPE/USDT:PERP"
      - "DOGE/USDT:PERP"
      - "ZEC/USDT:PERP"
      - "XLM/USDT:PERP"
      - "LINK/USDT:PERP"
      - "XMR/USDT:PERP"
      - "ADA/USDT:PERP"
      - "CC/USDT:PERP"
      - "BCH/USDT:PERP"
      - "GRAM/USDT:PERP"
      - "LTC/USDT:PERP"
      - "SUI/USDT:PERP"
      - "HBAR/USDT:PERP"
      - "AVAX/USDT:PERP"
      - "NEAR/USDT:PERP"
      - "1000SHIB/USDT:PERP"
      - "XAUT/USDT:PERP"
      - "UNI/USDT:PERP"
      - "TAO/USDT:PERP"
      - "WLFI/USDT:PERP"
      - "PAXG/USDT:PERP"
      - "ONDO/USDT:PERP"
      - "ASTER/USDT:PERP"
      - "M/USDT:PERP"
      - "DEXE/USDT:PERP"
      - "SKY/USDT:PERP"
      - "AAVE/USDT:PERP"
      - "DOT/USDT:PERP"
      - "MORPHO/USDT:PERP"
      - "WLD/USDT:PERP"
      - "1000PEPE/USDT:PERP"
      - "ICP/USDT:PERP"
      - "ETC/USDT:PERP"
      - "QNT/USDT:PERP"
      - "POL/USDT:PERP"
      - "JST/USDT:PERP"
      - "PUMP/USDT:PERP"
      - "ENA/USDT:PERP"
      - "ATOM/USDT:PERP"
      - "RENDER/USDT:PERP"
      - "KAS/USDT:PERP"
      - "BEAT/USDT:PERP"
      - "ALGO/USDT:PERP"
      - "JUP/USDT:PERP"
      - "ARB/USDT:PERP"
      - "FIL/USDT:PERP"
      - "VVV/USDT:PERP"
      - "LIT/USDT:PERP"
      - "INJ/USDT:PERP"
      - "APT/USDT:PERP"
      - "CAKE/USDT:PERP"
      - "NIGHT/USDT:PERP"
      - "AERO/USDT:PERP"
      - "DASH/USDT:PERP"
      - "ETHFI/USDT:PERP"
      - "VET/USDT:PERP"
      - "VIRTUAL/USDT:PERP"
      - "PENGU/USDT:PERP"
      - "PYTH/USDT:PERP"
      - "TRUMP/USDT:PERP"
      - "SUN/USDT:PERP"
      - "TIA/USDT:PERP"
      - "FET/USDT:PERP"
      - "CRV/USDT:PERP"
      - "SPX/USDT:PERP"
      - "1000LUNC/USDT:PERP"
      - "SEI/USDT:PERP"
      - "STX/USDT:PERP"
      - "JTO/USDT:PERP"
      - "LDO/USDT:PERP"
      - "ZRO/USDT:PERP"
      - "PENDLE/USDT:PERP"
      - "1000BONK/USDT:PERP"
      - "BSV/USDT:PERP"
      - "KITE/USDT:PERP"
      - "MON/USDT:PERP"
      - "XTZ/USDT:PERP"
      - "KAITO/USDT:PERP"
      - "CFX/USDT:PERP"
      - "UB/USDT:PERP"
      - "B/USDT:PERP"
      - "JASMY/USDT:PERP"
      - "GRASS/USDT:PERP"
      - "2Z/USDT:PERP"
      - "VELVET/USDT:PERP"
      - "XPL/USDT:PERP"
      - "OP/USDT:PERP"
      - "SYRUP/USDT:PERP"
      - "1000FLOKI/USDT:PERP"
      - "STRK/USDT:PERP"
      - "KAIA/USDT:PERP"
      - "ENS/USDT:PERP"
      - "PIEVERSE/USDT:PERP"
      - "GRT/USDT:PERP"
      - "FF/USDT:PERP"
      - "EIGEN/USDT:PERP"
      - "COMP/USDT:PERP"
      - "IOTA/USDT:PERP"
      - "CHZ/USDT:PERP"
      - "AXS/USDT:PERP"
      - "1000XEC/USDT:PERP"
      - "AKT/USDT:PERP"
      - "WIF/USDT:PERP"
      - "RUNE/USDT:PERP"

flusher:
  interval_seconds: 30
  max_batch_size: 1000
